name: C++ CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install build tools
      run: sudo apt-get install -y build-essential

    - name: Build with Make
      run: make all
